"""adding models

Revision ID: 791b1da8cfe7
Revises: d4aff2e52f47
Create Date: 2023-07-16 18:51:22.931113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791b1da8cfe7'
down_revision = 'd4aff2e52f47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('required', sa.BOOLEAN(), nullable=True),
    sa.Column('acquired', sa.BOOLEAN(), nullable=True),
    sa.Column('is_collection', sa.BOOLEAN(), nullable=True),
    sa.Column('allows', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialoptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('climb', sa.BOOLEAN(), nullable=True),
    sa.Column('dig', sa.BOOLEAN(), nullable=True),
    sa.Column('chop', sa.BOOLEAN(), nullable=True),
    sa.Column('meditate', sa.BOOLEAN(), nullable=True),
    sa.Column('portal', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('has_pine_cone', sa.BOOLEAN(), nullable=True),
    sa.Column('specialoptions', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flag'], ['flags.id'], ),
    sa.ForeignKeyConstraint(['specialoptions'], ['specialoptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiles',
    sa.Column('coordinates', sa.String(length=2), nullable=False),
    sa.Column('art', sa.String(), nullable=True),
    sa.Column('north', sa.String(length=2), nullable=True),
    sa.Column('east', sa.String(length=2), nullable=True),
    sa.Column('south', sa.String(length=2), nullable=True),
    sa.Column('west', sa.String(length=2), nullable=True),
    sa.Column('contents', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contents'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['east'], ['tiles.coordinates'], ),
    sa.ForeignKeyConstraint(['north'], ['tiles.coordinates'], ),
    sa.ForeignKeyConstraint(['south'], ['tiles.coordinates'], ),
    sa.ForeignKeyConstraint(['west'], ['tiles.coordinates'], ),
    sa.PrimaryKeyConstraint('coordinates')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tiles')
    op.drop_table('contents')
    op.drop_table('specialoptions')
    op.drop_table('flags')
    # ### end Alembic commands ###
